services:
  papierjs:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ALLOWED_HOST=${ALLOWED_HOST}
    ports:
      - "6006:6006"
    volumes:
      - .:/app
    command: ["npm", "run", "storybook"]
