/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PAccordion {
        "open": boolean;
        "title": string;
    }
    interface PAlert {
        /**
          * Show close icon
         */
        "closable"?: boolean;
        "dark"?: boolean;
        "type"?: AlertColor;
    }
    interface PBadge {
        "dark"?: boolean;
        "type"?: BadgeColor;
    }
    interface PBreadcrumb {
        "dark"?: boolean;
    }
    interface PBreadcrumbItem {
        "dark"?: boolean;
        "first"?: boolean;
        "link"?: string;
    }
    interface PButton {
        "block"?: boolean;
        "dark"?: boolean;
        "disabled"?: boolean;
        "large"?: boolean;
        "outline"?: boolean;
        "small"?: boolean;
        "type"?: ButtonColor;
    }
    interface PDropdown {
        "dark"?: boolean;
        "placeholder"?: string;
        /**
          * Prevent dropdown self update selected value
         */
        "preventSelected"?: boolean;
        /**
          * Selected item value
         */
        "value"?: string;
    }
    interface PDropdownItem {
        "dark"?: boolean;
        "selected"?: boolean;
        "value": string;
    }
    interface PDropdownPreview {
    }
    interface PInputText {
        "block"?: boolean;
        "dark"?: boolean;
        "disabled"?: boolean;
        "hasError"?: boolean;
        "label"?: string;
        "placeholder"?: string;
        "required"?: boolean;
        "value"?: string;
    }
    interface PLeaf {
        "dark"?: boolean;
    }
    interface PModal {
        "close": () => Promise<void>;
        "open": () => Promise<void>;
    }
    interface PModalPreview {
        "title"?: boolean;
    }
    interface PProgressBar {
        "dark"?: boolean;
        "striped"?: boolean;
        "type"?: ProgressBarColor;
        "value"?: number;
    }
    interface PSlider {
        "block"?: boolean;
        "dark"?: boolean;
        "max"?: number;
        "min"?: number;
        "value"?: number;
    }
    interface PSwitch {
        "checked"?: boolean;
        "dark"?: boolean;
        /**
          * define switch style
         */
        "round"?: boolean;
        /**
          * define switch parent style
         */
        "square"?: boolean;
    }
    interface PSwitchTile {
        "checked"?: boolean;
        "checkedBackground"?: TileBackground;
        /**
          * Enable dark mode
         */
        "dark"?: boolean;
        "uncheckedBackground"?: TileBackground;
    }
    interface PTab {
        "dark"?: boolean;
        "selected"?: boolean;
        "title": string;
    }
    interface PTabs {
        "dark"?: boolean;
    }
    interface PTooltip {
        "bottom"?: boolean;
        "disabled"?: boolean;
        "left"?: boolean;
        "right"?: boolean;
        "title"?: string;
        "top"?: boolean;
    }
}
export interface PAlertCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPAlertElement;
}
export interface PDropdownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPDropdownElement;
}
export interface PDropdownItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPDropdownItemElement;
}
export interface PInputTextCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPInputTextElement;
}
export interface PModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPModalElement;
}
export interface PSliderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPSliderElement;
}
export interface PSwitchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPSwitchElement;
}
export interface PSwitchTileCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPSwitchTileElement;
}
declare global {
    interface HTMLPAccordionElement extends Components.PAccordion, HTMLStencilElement {
    }
    var HTMLPAccordionElement: {
        prototype: HTMLPAccordionElement;
        new (): HTMLPAccordionElement;
    };
    interface HTMLPAlertElementEventMap {
        "close": any;
    }
    interface HTMLPAlertElement extends Components.PAlert, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPAlertElementEventMap>(type: K, listener: (this: HTMLPAlertElement, ev: PAlertCustomEvent<HTMLPAlertElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPAlertElementEventMap>(type: K, listener: (this: HTMLPAlertElement, ev: PAlertCustomEvent<HTMLPAlertElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPAlertElement: {
        prototype: HTMLPAlertElement;
        new (): HTMLPAlertElement;
    };
    interface HTMLPBadgeElement extends Components.PBadge, HTMLStencilElement {
    }
    var HTMLPBadgeElement: {
        prototype: HTMLPBadgeElement;
        new (): HTMLPBadgeElement;
    };
    interface HTMLPBreadcrumbElement extends Components.PBreadcrumb, HTMLStencilElement {
    }
    var HTMLPBreadcrumbElement: {
        prototype: HTMLPBreadcrumbElement;
        new (): HTMLPBreadcrumbElement;
    };
    interface HTMLPBreadcrumbItemElement extends Components.PBreadcrumbItem, HTMLStencilElement {
    }
    var HTMLPBreadcrumbItemElement: {
        prototype: HTMLPBreadcrumbItemElement;
        new (): HTMLPBreadcrumbItemElement;
    };
    interface HTMLPButtonElement extends Components.PButton, HTMLStencilElement {
    }
    var HTMLPButtonElement: {
        prototype: HTMLPButtonElement;
        new (): HTMLPButtonElement;
    };
    interface HTMLPDropdownElementEventMap {
        "select": string;
    }
    interface HTMLPDropdownElement extends Components.PDropdown, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPDropdownElementEventMap>(type: K, listener: (this: HTMLPDropdownElement, ev: PDropdownCustomEvent<HTMLPDropdownElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPDropdownElementEventMap>(type: K, listener: (this: HTMLPDropdownElement, ev: PDropdownCustomEvent<HTMLPDropdownElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPDropdownElement: {
        prototype: HTMLPDropdownElement;
        new (): HTMLPDropdownElement;
    };
    interface HTMLPDropdownItemElementEventMap {
        "change": string;
    }
    interface HTMLPDropdownItemElement extends Components.PDropdownItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPDropdownItemElementEventMap>(type: K, listener: (this: HTMLPDropdownItemElement, ev: PDropdownItemCustomEvent<HTMLPDropdownItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPDropdownItemElementEventMap>(type: K, listener: (this: HTMLPDropdownItemElement, ev: PDropdownItemCustomEvent<HTMLPDropdownItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPDropdownItemElement: {
        prototype: HTMLPDropdownItemElement;
        new (): HTMLPDropdownItemElement;
    };
    interface HTMLPDropdownPreviewElement extends Components.PDropdownPreview, HTMLStencilElement {
    }
    var HTMLPDropdownPreviewElement: {
        prototype: HTMLPDropdownPreviewElement;
        new (): HTMLPDropdownPreviewElement;
    };
    interface HTMLPInputTextElementEventMap {
        "change": string;
    }
    interface HTMLPInputTextElement extends Components.PInputText, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPInputTextElementEventMap>(type: K, listener: (this: HTMLPInputTextElement, ev: PInputTextCustomEvent<HTMLPInputTextElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPInputTextElementEventMap>(type: K, listener: (this: HTMLPInputTextElement, ev: PInputTextCustomEvent<HTMLPInputTextElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPInputTextElement: {
        prototype: HTMLPInputTextElement;
        new (): HTMLPInputTextElement;
    };
    interface HTMLPLeafElement extends Components.PLeaf, HTMLStencilElement {
    }
    var HTMLPLeafElement: {
        prototype: HTMLPLeafElement;
        new (): HTMLPLeafElement;
    };
    interface HTMLPModalElementEventMap {
        "close": void;
    }
    interface HTMLPModalElement extends Components.PModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPModalElementEventMap>(type: K, listener: (this: HTMLPModalElement, ev: PModalCustomEvent<HTMLPModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPModalElementEventMap>(type: K, listener: (this: HTMLPModalElement, ev: PModalCustomEvent<HTMLPModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPModalElement: {
        prototype: HTMLPModalElement;
        new (): HTMLPModalElement;
    };
    interface HTMLPModalPreviewElement extends Components.PModalPreview, HTMLStencilElement {
    }
    var HTMLPModalPreviewElement: {
        prototype: HTMLPModalPreviewElement;
        new (): HTMLPModalPreviewElement;
    };
    interface HTMLPProgressBarElement extends Components.PProgressBar, HTMLStencilElement {
    }
    var HTMLPProgressBarElement: {
        prototype: HTMLPProgressBarElement;
        new (): HTMLPProgressBarElement;
    };
    interface HTMLPSliderElementEventMap {
        "change": number;
    }
    interface HTMLPSliderElement extends Components.PSlider, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPSliderElementEventMap>(type: K, listener: (this: HTMLPSliderElement, ev: PSliderCustomEvent<HTMLPSliderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPSliderElementEventMap>(type: K, listener: (this: HTMLPSliderElement, ev: PSliderCustomEvent<HTMLPSliderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPSliderElement: {
        prototype: HTMLPSliderElement;
        new (): HTMLPSliderElement;
    };
    interface HTMLPSwitchElementEventMap {
        "change": boolean;
    }
    interface HTMLPSwitchElement extends Components.PSwitch, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPSwitchElementEventMap>(type: K, listener: (this: HTMLPSwitchElement, ev: PSwitchCustomEvent<HTMLPSwitchElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPSwitchElementEventMap>(type: K, listener: (this: HTMLPSwitchElement, ev: PSwitchCustomEvent<HTMLPSwitchElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPSwitchElement: {
        prototype: HTMLPSwitchElement;
        new (): HTMLPSwitchElement;
    };
    interface HTMLPSwitchTileElementEventMap {
        "change": boolean;
    }
    interface HTMLPSwitchTileElement extends Components.PSwitchTile, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPSwitchTileElementEventMap>(type: K, listener: (this: HTMLPSwitchTileElement, ev: PSwitchTileCustomEvent<HTMLPSwitchTileElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPSwitchTileElementEventMap>(type: K, listener: (this: HTMLPSwitchTileElement, ev: PSwitchTileCustomEvent<HTMLPSwitchTileElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPSwitchTileElement: {
        prototype: HTMLPSwitchTileElement;
        new (): HTMLPSwitchTileElement;
    };
    interface HTMLPTabElement extends Components.PTab, HTMLStencilElement {
    }
    var HTMLPTabElement: {
        prototype: HTMLPTabElement;
        new (): HTMLPTabElement;
    };
    interface HTMLPTabsElement extends Components.PTabs, HTMLStencilElement {
    }
    var HTMLPTabsElement: {
        prototype: HTMLPTabsElement;
        new (): HTMLPTabsElement;
    };
    interface HTMLPTooltipElement extends Components.PTooltip, HTMLStencilElement {
    }
    var HTMLPTooltipElement: {
        prototype: HTMLPTooltipElement;
        new (): HTMLPTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "p-accordion": HTMLPAccordionElement;
        "p-alert": HTMLPAlertElement;
        "p-badge": HTMLPBadgeElement;
        "p-breadcrumb": HTMLPBreadcrumbElement;
        "p-breadcrumb-item": HTMLPBreadcrumbItemElement;
        "p-button": HTMLPButtonElement;
        "p-dropdown": HTMLPDropdownElement;
        "p-dropdown-item": HTMLPDropdownItemElement;
        "p-dropdown-preview": HTMLPDropdownPreviewElement;
        "p-input-text": HTMLPInputTextElement;
        "p-leaf": HTMLPLeafElement;
        "p-modal": HTMLPModalElement;
        "p-modal-preview": HTMLPModalPreviewElement;
        "p-progress-bar": HTMLPProgressBarElement;
        "p-slider": HTMLPSliderElement;
        "p-switch": HTMLPSwitchElement;
        "p-switch-tile": HTMLPSwitchTileElement;
        "p-tab": HTMLPTabElement;
        "p-tabs": HTMLPTabsElement;
        "p-tooltip": HTMLPTooltipElement;
    }
}
declare namespace LocalJSX {
    interface PAccordion {
        "open"?: boolean;
        "title"?: string;
    }
    interface PAlert {
        /**
          * Show close icon
         */
        "closable"?: boolean;
        "dark"?: boolean;
        "onClose"?: (event: PAlertCustomEvent<any>) => void;
        "type"?: AlertColor;
    }
    interface PBadge {
        "dark"?: boolean;
        "type"?: BadgeColor;
    }
    interface PBreadcrumb {
        "dark"?: boolean;
    }
    interface PBreadcrumbItem {
        "dark"?: boolean;
        "first"?: boolean;
        "link"?: string;
    }
    interface PButton {
        "block"?: boolean;
        "dark"?: boolean;
        "disabled"?: boolean;
        "large"?: boolean;
        "outline"?: boolean;
        "small"?: boolean;
        "type"?: ButtonColor;
    }
    interface PDropdown {
        "dark"?: boolean;
        "onSelect"?: (event: PDropdownCustomEvent<string>) => void;
        "placeholder"?: string;
        /**
          * Prevent dropdown self update selected value
         */
        "preventSelected"?: boolean;
        /**
          * Selected item value
         */
        "value"?: string;
    }
    interface PDropdownItem {
        "dark"?: boolean;
        "onChange"?: (event: PDropdownItemCustomEvent<string>) => void;
        "selected"?: boolean;
        "value": string;
    }
    interface PDropdownPreview {
    }
    interface PInputText {
        "block"?: boolean;
        "dark"?: boolean;
        "disabled"?: boolean;
        "hasError"?: boolean;
        "label"?: string;
        "onChange"?: (event: PInputTextCustomEvent<string>) => void;
        "placeholder"?: string;
        "required"?: boolean;
        "value"?: string;
    }
    interface PLeaf {
        "dark"?: boolean;
    }
    interface PModal {
        "onClose"?: (event: PModalCustomEvent<void>) => void;
    }
    interface PModalPreview {
        "title"?: boolean;
    }
    interface PProgressBar {
        "dark"?: boolean;
        "striped"?: boolean;
        "type"?: ProgressBarColor;
        "value"?: number;
    }
    interface PSlider {
        "block"?: boolean;
        "dark"?: boolean;
        "max"?: number;
        "min"?: number;
        "onChange"?: (event: PSliderCustomEvent<number>) => void;
        "value"?: number;
    }
    interface PSwitch {
        "checked"?: boolean;
        "dark"?: boolean;
        "onChange"?: (event: PSwitchCustomEvent<boolean>) => void;
        /**
          * define switch style
         */
        "round"?: boolean;
        /**
          * define switch parent style
         */
        "square"?: boolean;
    }
    interface PSwitchTile {
        "checked"?: boolean;
        "checkedBackground"?: TileBackground;
        /**
          * Enable dark mode
         */
        "dark"?: boolean;
        "onChange"?: (event: PSwitchTileCustomEvent<boolean>) => void;
        "uncheckedBackground"?: TileBackground;
    }
    interface PTab {
        "dark"?: boolean;
        "selected"?: boolean;
        "title"?: string;
    }
    interface PTabs {
        "dark"?: boolean;
    }
    interface PTooltip {
        "bottom"?: boolean;
        "disabled"?: boolean;
        "left"?: boolean;
        "right"?: boolean;
        "title"?: string;
        "top"?: boolean;
    }
    interface IntrinsicElements {
        "p-accordion": PAccordion;
        "p-alert": PAlert;
        "p-badge": PBadge;
        "p-breadcrumb": PBreadcrumb;
        "p-breadcrumb-item": PBreadcrumbItem;
        "p-button": PButton;
        "p-dropdown": PDropdown;
        "p-dropdown-item": PDropdownItem;
        "p-dropdown-preview": PDropdownPreview;
        "p-input-text": PInputText;
        "p-leaf": PLeaf;
        "p-modal": PModal;
        "p-modal-preview": PModalPreview;
        "p-progress-bar": PProgressBar;
        "p-slider": PSlider;
        "p-switch": PSwitch;
        "p-switch-tile": PSwitchTile;
        "p-tab": PTab;
        "p-tabs": PTabs;
        "p-tooltip": PTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "p-accordion": LocalJSX.PAccordion & JSXBase.HTMLAttributes<HTMLPAccordionElement>;
            "p-alert": LocalJSX.PAlert & JSXBase.HTMLAttributes<HTMLPAlertElement>;
            "p-badge": LocalJSX.PBadge & JSXBase.HTMLAttributes<HTMLPBadgeElement>;
            "p-breadcrumb": LocalJSX.PBreadcrumb & JSXBase.HTMLAttributes<HTMLPBreadcrumbElement>;
            "p-breadcrumb-item": LocalJSX.PBreadcrumbItem & JSXBase.HTMLAttributes<HTMLPBreadcrumbItemElement>;
            "p-button": LocalJSX.PButton & JSXBase.HTMLAttributes<HTMLPButtonElement>;
            "p-dropdown": LocalJSX.PDropdown & JSXBase.HTMLAttributes<HTMLPDropdownElement>;
            "p-dropdown-item": LocalJSX.PDropdownItem & JSXBase.HTMLAttributes<HTMLPDropdownItemElement>;
            "p-dropdown-preview": LocalJSX.PDropdownPreview & JSXBase.HTMLAttributes<HTMLPDropdownPreviewElement>;
            "p-input-text": LocalJSX.PInputText & JSXBase.HTMLAttributes<HTMLPInputTextElement>;
            "p-leaf": LocalJSX.PLeaf & JSXBase.HTMLAttributes<HTMLPLeafElement>;
            "p-modal": LocalJSX.PModal & JSXBase.HTMLAttributes<HTMLPModalElement>;
            "p-modal-preview": LocalJSX.PModalPreview & JSXBase.HTMLAttributes<HTMLPModalPreviewElement>;
            "p-progress-bar": LocalJSX.PProgressBar & JSXBase.HTMLAttributes<HTMLPProgressBarElement>;
            "p-slider": LocalJSX.PSlider & JSXBase.HTMLAttributes<HTMLPSliderElement>;
            "p-switch": LocalJSX.PSwitch & JSXBase.HTMLAttributes<HTMLPSwitchElement>;
            "p-switch-tile": LocalJSX.PSwitchTile & JSXBase.HTMLAttributes<HTMLPSwitchTileElement>;
            "p-tab": LocalJSX.PTab & JSXBase.HTMLAttributes<HTMLPTabElement>;
            "p-tabs": LocalJSX.PTabs & JSXBase.HTMLAttributes<HTMLPTabsElement>;
            "p-tooltip": LocalJSX.PTooltip & JSXBase.HTMLAttributes<HTMLPTooltipElement>;
        }
    }
}
