/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PButton {
        "block"?: boolean;
        "dark"?: boolean;
        "disabled"?: boolean;
        "large"?: boolean;
        "outline"?: boolean;
        "small"?: boolean;
        "type"?: ButtonColor;
    }
    interface PProgressBar {
        "dark"?: boolean;
        "striped"?: boolean;
        "type"?: ProgressBarColor;
        "value"?: number;
    }
}
declare global {
    interface HTMLPButtonElement extends Components.PButton, HTMLStencilElement {
    }
    var HTMLPButtonElement: {
        prototype: HTMLPButtonElement;
        new (): HTMLPButtonElement;
    };
    interface HTMLPProgressBarElement extends Components.PProgressBar, HTMLStencilElement {
    }
    var HTMLPProgressBarElement: {
        prototype: HTMLPProgressBarElement;
        new (): HTMLPProgressBarElement;
    };
    interface HTMLElementTagNameMap {
        "p-button": HTMLPButtonElement;
        "p-progress-bar": HTMLPProgressBarElement;
    }
}
declare namespace LocalJSX {
    interface PButton {
        "block"?: boolean;
        "dark"?: boolean;
        "disabled"?: boolean;
        "large"?: boolean;
        "outline"?: boolean;
        "small"?: boolean;
        "type"?: ButtonColor;
    }
    interface PProgressBar {
        "dark"?: boolean;
        "striped"?: boolean;
        "type"?: ProgressBarColor;
        "value"?: number;
    }
    interface IntrinsicElements {
        "p-button": PButton;
        "p-progress-bar": PProgressBar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "p-button": LocalJSX.PButton & JSXBase.HTMLAttributes<HTMLPButtonElement>;
            "p-progress-bar": LocalJSX.PProgressBar & JSXBase.HTMLAttributes<HTMLPProgressBarElement>;
        }
    }
}
